name: CI

on: [pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changed-files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - id: tests
        run: ./scripts/tests.sh
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all }}

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: tests
        run: ./scripts/integration.sh
